CLASS zbp_r_recetas_arr DEFINITION
  PUBLIC ABSTRACT FINAL
  FOR BEHAVIOR OF zr_recetas_arr.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_r_recetas_arr IMPLEMENTATION.
ENDCLASS.
